### ISSUE TITLE
Deployment and testing steps

### ISSUE THREAD

**Issue by ljosyula** [airavata-courses/NetBoox#100]
Steps for deployment and testing are not updated on the wiki yet. Kindly, let me know as soon as you update the steps.
Thank you

**Comment by ljosyula** [comment]
Hi Team,
Can you please provide the below deliverables : 
1- Application URL to test the functioning of the application.
2- Jenkins URL to test the deployment
3- Kubernetes dashboard to check the health of the pods

Kindly let me know when you update the wiki with steps needed to be followed.

Thank you

**Comment by harshallpandit** [comment]
Jenkins URL -
http://149.165.170.200:8080/

Commit on jersey_service, 8-microservice-flask, 5-Microservice-in-Node-JS to initiate build for that particular service.

Links to test:
TACC:
http://129.114.104.238:30003/Netbux_Microservice/netbux/authors/getAuthors
http://129.114.104.238:30003/Netbux_Microservice/netbux/books/getBooks
http://129.114.104.238:30003/Netbux_Microservice/netbux/authors/getAuthorById/5bce308c26cda927f84754ea
http://129.114.104.238:30003/Netbux_Microservice/netbux/books/getBookById/5bce2a0ceb701011b6151a7b

IU:
http://149.165.170.107:30003/Netbux_Microservice/netbux/books/getBookById/5bce2a0ceb701011b6151a7b
http://149.165.170.107:30003/Netbux_Microservice/netbux/authors/getAuthors
http://149.165.170.107:30003/Netbux_Microservice/netbux/authors/getAuthorById/5bce308c26cda927f84754ea
http://149.165.170.107:30003/Netbux_Microservice/netbux/books/getBooks

NodeJs:
IU:
http://149.165.170.107:30001/graphql

TACC:
http://129.114.104.108:30001/graphql

Then follow the instructions on NodeJs service page.
https://github.com/airavata-courses/NetBoox/wiki/Node-JS-Microservice

Python:
IU:
http://149.165.170.107:30002/

TACC:
http://129.114.104.113:30002/

Then follow the instructions on python service page.
https://github.com/airavata-courses/NetBoox/wiki/Python-Flask-Microservice


We have not used Kubernetes dashboard, I can send you the screenshot of the Kubernetes deployment.

**Comment by ljosyula** [comment]
Hi Harshal,

Thank you for the links.
I opened all the URLs and everything seems to run fine. I made commits on the mentioned branches as well and can see the services getting build in Jenkins.

GraphiQL is also running fine for all the commands except for update users.
Since there was no instructions on what changes to make in the query to make it work I tried changing the id as well changing details keeping the id constant but it failed. PLease find the screenshot below.

![tacc_update id chaaneg fine](https://user-images.githubusercontent.com/42261978/49778722-7e7a2300-fcd4-11e8-9099-2340c7e47c5f.JPG)

![tacc_update email chaaneg fine](https://user-images.githubusercontent.com/42261978/49778726-82a64080-fcd4-11e8-9513-14d7edb2ad83.JPG)

Also, I opened the URL for the python service, it just showed the message saying "You reached the Python service"
and the instructions that you mentioned makes me deploy and run the service from my local machine while we are to test the service deployed on Jenkins server, Kindly correct me if I am wrong.

Please let me know how I can test your overall Application. All the services mentioned are working great.

Thank you

**Comment by harshallpandit** [comment]
Hi Soumya,
Please add the path(given on wiki page) after the IP address of the server.

eg.
http://129.114.104.113:30002/manage_subscription/findAllUsers

**Comment by ljosyula** [comment]
Hi Harshal and Sagar,

Thank you for the link, I can see the subscription details with the given URL.
As discussed with Sagar, I opened the browser as suggested and was able to access the UI of the application.
I was successfully able to create an account, login into the application ( gave incorrect password message for the wrong password) and was able to access the books present.
I was also able to access My profile and manage subscription and able to update the users through graphiql as suggested.

Great work!

Thank you.

**Comment by ljosyula** [comment]
Closing the issue.
