### ISSUE TITLE
Jersey service link for getAuthors not opening

### ISSUE THREAD

**Issue by ljosyula** [airavata-courses/NetBoox#57]
We are not able to open the below link provided in the wiki page unde Jersey service:

http://149.165.170.232:8080/Netbux_Microservice/netbux/books/getAuthors

Below is the screenshot for the same:

![1](https://user-images.githubusercontent.com/42261978/47605790-19df5f00-d9d9-11e8-891c-81fb90966852.JPG)

**Comment by harshallpandit** [comment]
Your link is incorrect. Change books/getAuthors to authors/getAuthors.

**Comment by harshallpandit** [comment]
Hi Soumya, it was a typo. I fixed it. Thanks for pointing it out.

**Comment by ljosyula** [comment]
Thank you.
Closing the issue.
