### ISSUE TITLE
Not able to run the queries in GraphiQL

### ISSUE THREAD

**Issue by ljosyula** [airavata-courses/NetBoox#58]
The first two queries are showing error and we are not able to run the third one.

Please find below screenshot for the same:

![2](https://user-images.githubusercontent.com/42261978/47605825-af7aee80-d9d9-11e8-8467-41d30bb248e6.JPG)
![3](https://user-images.githubusercontent.com/42261978/47605827-b1dd4880-d9d9-11e8-89e7-4a4fd98fab30.JPG)

I was not sure if we have to run all the queries in one go or separately so I tried running them in one go as well but I was not able to run it.

![4](https://user-images.githubusercontent.com/42261978/47605861-0d0f3b00-d9da-11e8-9f38-1807bfce929a.JPG)

**Comment by sagarpanchal8793** [comment]
Hello Soumya,

Thank you so much for providing us the appropriate screenshots, actually we updated the requirements and made some changes in the code but forgot to update the documents. So now the documentation is updated and tested.

For the third query, we cannot, execute all of them at once, all those are individual queries. I have updated the same in the documentation as well.

If possible kindly test again.

**Comment by ljosyula** [comment]
Hello Sagar,

Appreciate your quick response.
But, there still seems some issue with the first two queries. Please find below the screenshots for the same:

![1 1](https://user-images.githubusercontent.com/42261978/47606710-f0c4cb80-d9e4-11e8-846a-c200eb1bedad.JPG)

![1 2](https://user-images.githubusercontent.com/42261978/47606714-f4585280-d9e4-11e8-8d22-ca71710379bc.JPG)

The last two queries are working fine.

Thank you

**Comment by ljosyula** [comment]
The queries are working fine.

It would be really helpful if you could add some instructions on the wiki page.

Closing the issue.
Thank you
