### ISSUE TITLE
Change port numbers to works with Kubernetes

### ISSUE THREAD

**Issue by Keerthi4308** [airavata-courses/NetBoox#78]

**Comment by harshallpandit** [comment]
Closed by: 
4780e86fde1c16a4c7ddaacc7c32016ef19f8102

**Comment by sagarpanchal8793** [comment]
8284abd9412d10972734aa39b2c49a7cefe166af

8bdd23cbf8c10f5ee6a8d368c61265d9b77d41fd

**Comment by sagarpanchal8793** [comment]
ebf46ea3888a8ef6493a7599857df5339d902ea3

**Comment by sagarpanchal8793** [comment]
601da3a684388a15c381462369013c9960b80c84
